### ISSUE TITLE
Disposable.prototype.disposed?

### ISSUE THREAD

**Issue by sedabull** [atom/event-kit#9]
I was just reading through the source code here (for fun obviously :smiley:) and I noticed something peculiar [here](https://github.com/atom/event-kit/blob/v1.1.0/src/disposable.coffee#L7). This value `Disposable::disposed` is checked in [`Disposable::dispose`](https://github.com/atom/event-kit/blob/v1.1.0/src/disposable.coffee#L24-29) to determine if its `disposableAction` should be called. Now unless I am mistaken (and please feel free to correct me if I am) setting this value to true on line 26 the first time an instance calls this function will cause all other disposables not to be properly disposed. In other words, shouldn't this value exist on each individual instance and not be shared on the prototype? If so I'd be happy to open a PR to fix this as soon as possible.

**Comment by sedabull** [comment]
I just realized the same is true in the `CompositeDisposable` class

**Comment by sedabull** [comment]
Also on the `Emitter` class? I must be missing something here...could someone please fill me in?

**Comment by lee-dohm** [comment]
I tested your theory with the following spec:

```coffee
  it 'disposes only itself', ->
    disposalAction1 = jasmine.createSpy("dummy")
    disposalAction2 = jasmine.createSpy("dummy")
    disposable1 = new Disposable(disposalAction1)
    disposable2 = new Disposable(disposalAction2)

    disposable1.dispose()
    expect(disposable2.disposed).toBe false
```

It passed, so it appears that the `disposed` on `Disposable` is an instance variable after all.

**Comment by sedabull** [comment]
@lee-dohm, I've dug into this a little further and you are correct that `disposed` is an instance variable. However the only reason this is true is because for some reason **all** properties from `Disposable.prototype` are copied to each instance. Which means the `dispose` and `off` methods are present on each instance as well. See the attached screen shot for evidence:

![disposable](https://cloud.githubusercontent.com/assets/9311295/7551617/ee2e94be-f65d-11e4-8b5a-11e165f24685.png)

I'm not sure how this is happening, but it seems like a huge waste of memory. Unless I'm mistaken, the point of putting those two methods on the prototype is so that they can be shared between instances. Is this behavior intentional?

**Comment by sedabull** [comment]
To illustrate the point better I believe this test:

```coffeescript
it 'should not have any methods attached to an instance', ->
  disposable = new Disposable(->)
  jasmine.spyOn(Disposable.prototype, 'dispose').andCallThrough()
  disposable.dispose()
  expect(Disposable.prototype.dispose).toHaveBeenCalled()
```

will fail.
